name: Telegram Automatico Diario

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando codigo do GitHub
        uses: actions/checkout@v3

      - name: Instalando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalando Bibliotecas
        run: pip install yfinance pyTelegramBotAPI pandas

      - name: Executando o Robo
        run: python bot_telegram.py
